---
output:
  pdf_document:
    fig_caption: no
    number_sections: no
    toc: yes
    toc_depth: 2
    # github_document:
    # html_preview: yes
    # toc: yes
    # toc_depth: 2
editor_options: 
  chunk_output_type: inline
---

# Dependencies
```{r setup, message=FALSE}
library(ggplot2)
library(tibble)
library(cowplot)
library(beepr)
library(Rfast)
library(changepoint)
library(mcp)
library(rjags)
library(mutoss)
library(ecp)
source("./code/functions.R")
source("./code/theme_gar.txt")
# Edit `one_over_f` function from `primer` package to control variance (Stevens, 2009). 
# Original function is available on [GitHub](https://github.com/HankStevens/primer).
# Copyright Hank Stevens.
source("./code/one_over_f.R")
# Load template: true onset = 160 ms, F=81, max at F=126
source("./code/erp_template.R")
# R version of Matlab code from Yeung et al. 2004
source("./code/eeg_noise.R")
# Lodaing the code that gives median instead of mean values in mcp summary table
source("./code/mcp_median_function.R")
# to use with eeg_noise function
meanpower <- unlist(read.table("./code/meanpower.txt"))
```

Estimating onsets in a group of 20 simulated participants with a random effect onset between 150 and 170ms. Median onset is used as the group estimate. 
```{r eval=FALSE, warning=FALSE, include=FALSE}

# Creating a save function to save results incrementally, every 100 iterations 
save_results <- function(iteration, simres.cs, simres.fdr, simres.cp, simres.pelt, simres.mcp, simres.ecp) {
  filename <- sprintf("./group20_sim/main_sim_n50_eeg_group20_iter_%d.RData", iteration)
  save(simres.cs, simres.fdr, simres.cp, simres.pelt, simres.mcp, simres.ecp, file = filename)
}

ptm <- proc.time()
set.seed(666)
options(mc.cores = 3)
aath <- 0.05 # arbitrary alpha threshold
nsim <- 2000 # simulation iterations
nboot <- 2000 # number of permutation samples
inc.step <- 500 # console notification every inc.step iterations
srate <- 500 # sampling rate in Hz
ronset <- seq(150, 170, 2) # random onset for each participant

prior <- list(
  cp_1 = "dunif(100, 250)" # Change point expected between 100 and 250 ms
)

model <- list(
  y ~ 1 + sigma(1),
    ~ 0 + x + sigma(1)
)

Nt <- 50 # number of trials
Np <- 20 # number of participants
outvar <- 1 # noise variance

cond1 <- matrix(0, nrow = Nt, ncol = Nf)
cond2 <- matrix(0, nrow = Nt, ncol = Nf)

simres.cp <- matrix(NA, nrow = Np, ncol = nsim)
simres.fdr <- matrix(NA, nrow = Np, ncol = nsim)
simres.cs <- matrix(NA, nrow = Np, ncol = nsim)
simres.pelt <- matrix(NA, nrow = Np, ncol = nsim)
simres.ecp <- matrix(NA, nrow = Np, ncol = nsim)
simres.mcp <- matrix(NA, nrow = Np, ncol = nsim)

for(S in 1:nsim){
  
  # sim.counter(S, nsim, inc = inc.step) 
  
  for(P in 1:Np){ # participants
    
    ponset <- sample(ronset, 1) # get random onset
    st <- which(Xf==ponset)
    temp2 <- c(rep(0, st-2), erp, rep(0, Nf-st-length(erp)+2))

    for(T in 1:Nt){
      cond2[T,] <- temp2 + eeg_noise(frames = Nf, srate = srate, outvar = outvar, meanpower)
      cond1[T,] <- temp1 + eeg_noise(frames = Nf, srate = srate, outvar = outvar, meanpower)
    }
    
    # t-tests
    ori.t2 <- vector(mode = "numeric", length = Nf)
    for(F in 1:Nf){
      ori.t2[F] <- t.test(cond1[,F], cond2[,F])$statistic^2
    }
    
    ###############################################
    
    # Fit BinSeg model ----
    res <- cpt.meanvar(ori.t2, method = "BinSeg", Q=2)
    simres.cp[P,S] <- Xf[res@cpts[1]]
    
    ###############################################
    
    # Fit PELT with a penalty multiplier of 30 ----
    res.pelt <- cpt.meanvar(ori.t2, method = "PELT", penalty = "Manual", pen.value = 30*log(length(ori.t2)))
    simres.pelt[P,S] <- Xf[res.pelt@cpts[1]]
    
    ###############################################
    
    # Fit mcp model ----
    df <- tibble(x = Xf, y = ori.t2)

    fit <- mcp(model, prior = prior, data = df, cores = 3, chains = 3)

    summary.fit.median <- summary.mcpfit.median(fit)
    simres.mcp[P,S] <- round(summary.fit.median[1,2],0)
    
    ###############################################
    
    # Make permutation table of t values ----
    perm.t2 <- permtdist(cond1, cond2, Nt, Nf, nboot = nboot)^2
    perm.th <- apply(perm.t2, 2, quantile, probs = 1-aath)
    
    # FDR ----
    perm.pvals <- vector(mode = "numeric", length = Nf)
    for(F in 1:Nf){
      perm.pvals[F] <- (sum(perm.t2[,F] >= ori.t2[F]) + 1) / (nboot + 1)
    }
    fdr.pvals <- p.adjust(perm.pvals, method = "fdr")
    simres.fdr[P,S] <- Xf[which(fdr.pvals <= aath)[1]]
    
    ###############################################
    
    # cluster-sum statistics ----
    cmap <- cluster.make(perm.pvals <= aath)
    perm.max.sums <- vector(mode = "numeric", length = nboot)
    for(B in 1:nboot){
      # threshold permutation t2 values and form clusters
      perm.cmap <- cluster.make(perm.t2[B,] <= perm.th)  
      perm.max.sums[B] <- max(cluster.sum(values = perm.t2[B,], cmap = perm.cmap))
    }
    # cluster sum threshold
    cs.th <- quantile(perm.max.sums, probs = 1-aath)
    # cluster test
    cs.test <- cluster.test(values = ori.t2, cmap = cmap, cs.th)
    simres.cs[P,S] <- Xf[cs.test][1]
    
    ##############################################
    
    # Fit non-parametric e.cp3o_delta from ecp package
    ori.t2 <- matrix(ori.t2, ncol = 1) # ecp only accepts matrices 
    
    # Fit ecp cp3o_delta model ----
    result_cp3o_delta <- e.cp3o_delta(Z = ori.t2, K = 8, alpha = 1)
    simres.ecp[P,S] <- get_earliest_cp(result_cp3o_delta$estimates, Xf)
  }

  # Using the save_results function to save every 100 iterations of the simulation
  if (S %% 100 == 0 || S == nsim) {
    save_results(S, simres.cs, simres.fdr, simres.cp, simres.pelt, simres.mcp, simres.ecp)
  }
}

proc.time()-ptm
```

### Merging all of the files into 1

```{r}
# Set the directory containing the .RData files
setwd("./group20_sim/")

# List all .RData files in the directory
files <- list.files(pattern = "\\.RData$")

combined_simres_cs <- list()
combined_simres_fdr <- list()
combined_simres_cp <- list()
combined_simres_pelt <- list()
combined_simres_mcp <- list()
combined_simres_ecp <- list()

for (file in files) {
  load(file)
  
  # Append the valid parts of each data frame to the corresponding list
  combined_simres_cs[[file]] <- simres.cs[, 1:100]
  combined_simres_fdr[[file]] <- simres.fdr[, 1:100]
  combined_simres_cp[[file]] <- simres.cp[, 1:100]
  combined_simres_pelt[[file]] <- simres.pelt[, 1:100]
  combined_simres_mcp[[file]] <- simres.mcp[, 1:100]
  combined_simres_ecp[[file]] <- simres.ecp[, 1:100]
}

# Combine the lists into single data frames
simres.cs <- do.call(cbind, combined_simres_cs)
simres.fdr <- do.call(cbind, combined_simres_fdr)
simres.cp <- do.call(cbind, combined_simres_cp)
simres.pelt <- do.call(cbind, combined_simres_pelt)
simres.mcp <- do.call(cbind, combined_simres_mcp)
simres.ecp <- do.call(cbind, combined_simres_ecp)

save(simres.cs, file = "final_simres_cs.RData")
save(simres.fdr, file = "final_simres_fdr.RData")
save(simres.cp, file = "final_simres_cp.RData")
save(simres.pelt, file = "final_simres_pelt.RData")
save(simres.mcp, file = "final_simres_mcp.RData")
save(simres.ecp, file = "final_simres_ecp.RData")
```


## Plot onset distributions

```{r, warning=FALSE}
load("./group20_sim/final_simres_cs.RData")
load("./group20_sim/final_simres_fdr.RData")
load("./group20_sim/final_simres_cp.RData")
load("./group20_sim/final_simres_pelt.RData")
load("./group20_sim/final_simres_mcp.RData")
load("./group20_sim/final_simres_ecp.RData")

# compute group medians
simres.cs <- apply(simres.cs, 2, median, na.rm = TRUE)
simres.cp <- apply(simres.cp, 2, median, na.rm = TRUE)
simres.fdr <- apply(simres.fdr, 2, median, na.rm = TRUE)
simres.mcp <- apply(simres.mcp, 2, median, na.rm = TRUE)
simres.ecp <- apply(simres.ecp, 2, median, na.rm = TRUE)
simres.pelt <- apply(simres.pelt, 2, median, na.rm = TRUE)

# Colour palette from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
categ.palette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

df <- tibble(onsets = c(simres.cp, simres.cs, simres.fdr, simres.mcp, simres.ecp, simres.pelt),
             method = factor(c(rep("BinSeg", length(simres.cp)),
                               rep("CS", length(simres.cs)),
                               rep("FDR", length(simres.fdr)),
                               rep("mcp", length(simres.mcp)),
                               rep("ecp", length(simres.ecp)),
                               rep("PELT", length(simres.pelt))))
)

ggplot(data = df, aes(x = onsets, colour = method)) + theme_gar +
  # stat_density(geom = "line") +
  geom_freqpoly(fill = "white", na.rm = TRUE, breaks = Xf) +
  geom_vline(xintercept = true_onset, linetype = "solid") +
  # geom_vline(xintercept = median(simres.cp, na.rm = TRUE))
  scale_colour_manual(values = categ.palette) +
  theme(legend.position = c(.8, .8)) +
  labs(x = "Group median onsets in ms", y = "Count") +
  coord_cartesian(xlim = c(100, 300))

# ggsave(filename = "./figures/eeg_group_onset_dist.pdf", width = 10, height = 5)
# ggsave(filename = "./figures/figure5.pdf", width = 10, height = 5)
```

## Bias
```{r}
print("Bias:")
print(paste("FDR =",median(simres.fdr, na.rm = TRUE) - true_onset))
print(paste("Cluster =",median(simres.cs, na.rm = TRUE) - true_onset))
print(paste("BinSeg =",median(simres.cp, na.rm = TRUE) - true_onset))
print(paste("mcp =",median(simres.mcp, na.rm = TRUE) - true_onset))
print(paste("ecp =",median(simres.ecp, na.rm = TRUE) - true_onset))
print(paste("PELT =",median(simres.pelt, na.rm = TRUE) - true_onset))
```

## Mean absolute error 

```{r}
print("MAE:")
print(paste("FDR =",round(mean(abs(simres.fdr - true_onset), na.rm = TRUE), digits=1)))
print(paste("Cluster =",round(mean(abs(simres.cs - true_onset), na.rm = TRUE), digits=1)))
print(paste("BinSeg =",round(mean(abs(simres.cp - true_onset), na.rm = TRUE), digits=1)))
print(paste("mcp =",round(mean(abs(simres.mcp - true_onset), na.rm = TRUE), digits=1)))
print(paste("ecp =",round(mean(abs(simres.ecp - true_onset), na.rm = TRUE), digits=1)))
print(paste("PELT =",round(mean(abs(simres.pelt - true_onset), na.rm = TRUE), digits=1)))
```

## Variance 

```{r}
print("Variance:")
print(paste("FDR =",round(var(simres.fdr, na.rm = TRUE), digits=0)))
print(paste("Cluster =",round(var(simres.cs, na.rm = TRUE), digits=0)))
print(paste("BinSeg =",round(var(simres.cp, na.rm = TRUE), digits=0)))
print(paste("mcp =",round(var(simres.mcp, na.rm = TRUE), digits=0)))
print(paste("ecp =",round(var(simres.ecp, na.rm = TRUE), digits=0)))
print(paste("PELT =",round(var(simres.pelt, na.rm = TRUE), digits=0)))
```

## Proportion too early
```{r}
print("Proportion too early:")
print(paste("FDR =",round(100*mean((simres.fdr - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
print(paste("Cluster =",round(100*mean((simres.cs - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
print(paste("BinSeg =",round(100*mean((simres.cp - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
print(paste("mcp =",round(100*mean((simres.mcp - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
print(paste("ecp =",round(100*mean((simres.ecp - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
print(paste("PELT =",round(100*mean((simres.pelt - true_onset) < 0, na.rm = TRUE), digits=2),"%"))
```