---
output:
  pdf_document:
    fig_caption: no
    number_sections: no
    toc: yes
    toc_depth: 2
    # github_document:
    # html_preview: yes
    # toc: yes
    # toc_depth: 2
editor_options: 
  chunk_output_type: inline
---

# Dependencies
```{r setup, message=FALSE}
library(ggplot2)
library(tibble)
library(cowplot)
library(beepr)
library(Rfast)
library(changepoint)
library(mcp)
library(rjags)
library(mutoss)
source("./code/functions.R")
source("./code/theme_gar.txt")
# Edit `one_over_f` function from `primer` package to control variance (Stevens, 2009). 
# Original function is available on [GitHub](https://github.com/HankStevens/primer).
# Copyright Hank Stevens.
source("./code/one_over_f.R")
# Load template: true onset = 160 ms, F=81, max at F=126
source("./code/erp_template.R")
# R version of Matlab code from Yeung et al. 2004
source("./code/eeg_noise.R")
# Lodaing the code that gives median instead of mean values in mcp summary table
source("./code/mcp_median_function.R")
# to use with eeg_noise function
meanpower <- unlist(read.table("./code/meanpower.txt"))
```

### Running all models with 100-200ms limits

```{r warning=FALSE, include=FALSE}

ptm <- proc.time() # Timing code chunk execution

set.seed(666)
options(mc.cores = 3)
aath <- 0.05 # arbitrary alpha threshold
nsim <- 10000 # simulation iterations
nboot <- 2000 # number of permutation samples
simres.cp  <- vector(mode = "numeric", length = nsim) * NA
simres.cs  <- vector(mode = "numeric", length = nsim) * NA
simres.fdr <- vector(mode = "numeric", length = nsim) * NA
simres.mcp.median <- vector(mode = "numeric", length = nsim) * NA
simres.mcp.mean   <- vector(mode = "numeric", length = nsim) * NA
simres.pelt15 <- vector(mode = "numeric", length = nsim) * NA
simres.pelt30 <- vector(mode = "numeric", length = nsim) * NA

Nt <- 50 # number of trials
gsp <- 1 # gamma spectral power
outvar <- 1 # noise variance
cond1 <- matrix(0, nrow = Nt, ncol = Nf)
cond2 <- matrix(0, nrow = Nt, ncol = Nf)

for(S in 1:nsim){
  
  for(T in 1:Nt){
    cond2[T,] <- temp2 + one_over_f(gamma = gsp, Nf, outvar = outvar)
    cond1[T,] <- temp1 + one_over_f(gamma = gsp, Nf, outvar = outvar)  
  }
  # t-tests
  ori.t2 <- vector(mode = "numeric", length = Nf)
  for(F in 1:Nf){
    ori.t2[F] <- t.test(cond1[,F], cond2[,F])$statistic^2
  }
  
  # fit change point model
  res.cp <- cpt.meanvar(ori.t2, method = "BinSeg", Q=2)
  
  if (length(res.cp@cpts) > 0) {
  point <- Xf[res.cp@cpts[1]]
  filtered_points <- point[point >= 100 & point <= 200]
  simres.cp[S] <- if (length(filtered_points) > 0) filtered_points[1] else NA
} else {
  simres.cp[S] <- NA
}
  
  # fit mcp model
  df <- tibble(x = Xf, y = ori.t2)
  model <- list(
    y ~ 1 + sigma(1),
      ~ 0 + x + sigma(1)
  )
  
  prior <- list(
    cp_1 = "dunif(100, 200)" # Change point expected between 100 and 200 ms
  )
  
  fit <- mcp(model, data = df, prior = prior, cores = 3, chains = 3)
  
  summary.fit.median <- summary.mcpfit.median(fit)
  simres.mcp.median[S] <- round(summary.fit.median[1,2],0)
  
  # Fitting the same model but for the mean function to compare to median
  summary.fit.mean <- mcp:::summary.mcpfit(fit)
  simres.mcp.mean[S] <- round(summary.fit.mean[1,2],0)
  
  # Fit PELT with a penalty multiplier of 15
  res.pelt <- cpt.meanvar(ori.t2, method = "PELT", penalty = "Manual", pen.value = 15*log(length(ori.t2)))
  
    if (length(res.pelt@cpts) > 0) {
  point <- Xf[res.pelt@cpts[1]]
  filtered_points <- point[point >= 100 & point <= 200]
  simres.pelt15[S] <- if (length(filtered_points) > 0) filtered_points[1] else NA
} else {
  simres.pelt15[S] <- NA
}
  
  # Fit PELT with a penalty multiplier of 30
  res.pelt <- cpt.meanvar(ori.t2, method = "PELT", penalty = "Manual", pen.value = 30*log(length(ori.t2)))
  
  if (length(res.pelt@cpts) > 0) {
  point <- Xf[res.pelt@cpts[1]]
  filtered_points <- point[point >= 100 & point <= 200]
  simres.pelt30[S] <- if (length(filtered_points) > 0) filtered_points[1] else NA
} else {
  simres.pelt30[S] <- NA
}
  
  # Make permutation table of t values 
  perm.t2 <- permtdist(cond1, cond2, Nt, Nf, nboot = nboot)^2
  perm.th <- apply(perm.t2, 2, quantile, probs = 1-aath)
  
  perm.pvals <- vector(mode = "numeric", length = Nf)
  for(F in 1:Nf){
    perm.pvals[F] <- (sum(perm.t2[,F] >= ori.t2[F]) + 1) / (nboot + 1)
  }
  
  # FDR
  fdr.pvals <- p.adjust(perm.pvals, method = "fdr")
  fdr.res <- find_onset(fdr.pvals <= aath, Xf)
  
  if (!is.na(fdr.res) && fdr.res >= 100 && fdr.res <= 200) {
    simres.fdr[S] <- fdr.res
  } else {
    simres.fdr[S] <- NA
  }
  
  # cluster-sum statistics -----
  cmap <- cluster.make(perm.pvals <= aath)
  perm.max.sums <- vector(mode = "numeric", length = nboot)
  for(B in 1:nboot){
    # threshold permutation t2 values and form clusters
    perm.cmap <- cluster.make(perm.t2[B,] <= perm.th)  
    perm.max.sums[B] <- max(cluster.sum(values = perm.t2[B,], cmap = perm.cmap))
  }
  # cluster sum threshold
  cs.th <- quantile(perm.max.sums, probs = 1-aath)
  # cluster test
  cs.test <- cluster.test(values = ori.t2, cmap = cmap, cs.th)
  cs.res <- find_onset(cs.test, Xf)
  
  if (!is.na(cs.res) && cs.res >= 100 && cs.res <= 200) {
    simres.cs[S] <- cs.res
  } else {
    simres.cs[S] <- NA
  }
}

save(simres.cs, simres.cp, simres.fdr, simres.mcp.mean, simres.mcp.median, simres.pelt15, simres.pelt30,
     file = "./data/experimental_sim_limits.RData")

proc.time()-ptm
```

```{r, warning=FALSE, fig.height=8, fig.width=8}
load("./data/experimental_sim_limits.RData")

# Colour palette from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
categ.palette <- c("#000000", "#E69F00", "#009E73", "#0072B2", "#D55E00", "#CC79A7", "#F0E442")

df <- tibble(onsets = c(simres.cp, simres.cs, simres.mcp.median, simres.mcp.mean, simres.fdr, simres.pelt15, simres.pelt30),
             method = factor(c(rep("change point: BinSeg", length(simres.cp)),
                               rep("cluster sum", length(simres.cs)),
                               rep("mcp median", length(simres.mcp.median)),
                               rep("mcp mean", length(simres.mcp.mean)),
                               rep("FDR", length(simres.fdr)),
                               rep("Change point: PELT", length(simres.pelt15)),
                               rep("cp pelt30", length(simres.pelt30))
                              )))


ggplot(data = df, aes(x = onsets, colour = method)) + theme_gar +
  # stat_density(geom = "line") +
  geom_freqpoly(fill = "white", na.rm = TRUE, breaks = Xf) +
  geom_vline(xintercept = true_onset, linetype = "dashed") +
  # geom_vline(xintercept = median(simres.cp, na.rm = TRUE))
  scale_colour_manual(values = categ.palette) +
  theme(legend.position = c(.8, .8)) +
  labs(x = "Onsets in ms", y = "Count")
```

