---
output:
  pdf_document:
    fig_caption: no
    number_sections: no
    toc: yes
    toc_depth: 2
    # github_document:
    # html_preview: yes
    # toc: yes
    # toc_depth: 2
editor_options: 
  chunk_output_type: inline
---

# Dependencies
```{r setup, message=FALSE}
library(ggplot2)
library(tibble)
library(cowplot)
library(beepr)
library(Rfast)
library(changepoint)
library(mcp)
library(rjags)
library(mutoss)
library(ecp)
source("./code/functions.R")
source("./code/theme_gar.txt")
# Edit `one_over_f` function from `primer` package to control variance (Stevens, 2009). 
# Original function is available on [GitHub](https://github.com/HankStevens/primer).
# Copyright Hank Stevens.
source("./code/one_over_f.R")
# Load template: true onset = 160 ms, F=81, max at F=126
source("./code/erp_template.R")
# R version of Matlab code from Yeung et al. 2004
source("./code/eeg_noise.R")
# Lodaing the code that gives median instead of mean values in mcp summary table
source("./code/mcp_median_function.R")
# to use with eeg_noise function
meanpower <- unlist(read.table("./code/meanpower.txt"))
```

# Simulation: vary sample size

```{r eval=FALSE, message=TRUE, warning=FALSE, include=FALSE}
set.seed(33) 
options(mc.cores = 3)
aath <- 0.05 # arbitrary alpha threshold
nsim <- 10000 # simulation iterations
nboot <- 2 # number of permutation samples
srate <- 500 # sampling rate in Hz
n_vec <- seq(20,150,10) 
n_length <- length(n_vec)
n_max <- max(n_vec)
inc.step <- 500

# Matrices for each method
simres.mcp <- matrix(NA, nrow = n_length, ncol = nsim)

outvar <- 1 # noise variance
cond1_all <- matrix(0, nrow = n_max, ncol = Nf)
cond2_all <- matrix(0, nrow = n_max, ncol = Nf)

for(S in 1:nsim){
  
  sim.counter(S, nsim, inc = inc.step)
  
  # Generate all trials
  for(T in 1:n_max){
    cond2_all[T,] <- temp2 + eeg_noise(frames = Nf, srate = srate, outvar = outvar, meanpower)
    cond1_all[T,] <- temp1 + eeg_noise(frames = Nf, srate = srate, outvar = outvar, meanpower) 
  }
  
  for(N in 1:n_length){
    
    Nt <- n_vec[N]
    
    # downsample to current size
    cond2 <- cond2_all[1:Nt,]
    cond1 <- cond1_all[1:Nt,]
    
    # t-tests
    ori.t2 <- vector(mode = "numeric", length = Nf)
    for(F in 1:Nf){
      ori.t2[F] <- t.test(cond1[,F], cond2[,F])$statistic^2
    }
    
    #######################################
    
    # Fit mcp model
    df <- tibble(x = Xf, y = ori.t2)
    model <- list(
      y ~ 1 + sigma(1),
        ~ 0 + x + sigma(1)
    )
    
    prior <- list(
      cp_1 = "dunif(100, 250)" # Change point expected between 100 and 250 ms
    )
  
    fit <- mcp(model, prior = prior, data = df, cores = 3, chains = 3)
  
    summary.fit.median <- summary.mcpfit.median(fit)
    simres.mcp[N,S] <- round(summary.fit.median[1,2],0)
  
    ######################################
    
    if (S %% 100 == 0) {
      temp.simres7 <- simres.mcp[,1:S]
      save(temp.simres7, file = paste0("./vary_n_mcp_data7/vary_n_mcp_", S, ".RData"))
    }
  }
}

if (nsim %% 100 != 0) {
  temp.final <- simres.mcp
    save(temp.final, file = paste0("./vary_n_mcp_data7/vary_n_mcp_final.RData"))
}
# save(simres.mcp, file = "./data/vary_n_mcp.RData")
```

## Incremental saves merging
```{r}
load("./vary_n_mcp_data/vary_n_mcp_2000.RData")
load("./vary_n_mcp_data4/vary_n_mcp_2000.RData") # loads in as temp.simres2
temp.simres4 <- temp.simres2
load("./vary_n_mcp_data2/vary_n_mcp_2200.RData")
load("./vary_n_mcp_data3/vary_n_mcp_2000.RData")
load("./vary_n_mcp_data5/vary_n_mcp_700.RData")
load("./vary_n_mcp_data6/vary_n_mcp_700.RData")
load("./vary_n_mcp_data7/vary_n_mcp_400.RData")
save(simres.mcp, file = "./data/vary_n_mcp.RData")
var1 <- cbind(temp.simres, temp.simres2)
```

